import os
import sys
import logging
import time
import re
import json
import numpy as np
import pandas as pd
from dotenv import load_dotenv
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from groq import Groq
import groq

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)]
)
logger = logging.getLogger(__name__)

# Constants for Groq API
PRIMARY_MODEL = "llama-3.3-70b-versatile"
FALLBACK_MODEL = "llama-3.1-8b-instant"

def get_groq_client() -> Groq | None:
    """Initializes and returns the Groq client if the API key is configured."""
    api_key = os.getenv("GROQ_API_KEY")
    if not api_key or api_key == "your_groq_api_key_here":
        logger.warning("GROQ_API_KEY is not configured. Running in offline/fallback mode.")
        return None
    try:
        return Groq(api_key=api_key)
    except Exception as e:
        logger.error(f"Failed to initialize Groq client: {e}")
        return None

def clean_label(label: str) -> str:
    """Cleans the theme label generated by LLM (removes quotes, stars, extra punctuation)."""
    # Strip markdown bold stars, quotes, backticks
    label = re.sub(r'[\*"`\'_]', '', label).strip()
    # Strip trailing periods
    label = label.rstrip('.')
    # Ensure it's not empty and limit word count to 4 words
    words = label.split()
    if len(words) > 4:
        label = " ".join(words[:4])
    return label.title()

def extract_keyphrases_offline(texts: list[str]) -> str:
    """Offline fallback to generate cluster theme labels when Groq is unavailable."""
    stopwords = {
        "app", "the", "and", "for", "with", "this", "that", "easy", "simple", 
        "fast", "groww", "very", "good", "great", "nice", "best", "money", 
        "stock", "stocks", "funds", "mutual", "trading", "investing", "invest",
        "please", "not", "but", "are", "have", "you", "your", "can", "get"
    }
    words = []
    for t in texts:
        # Extract word tokens of length >= 3
        for w in re.findall(r"\b[a-zA-Z]{3,}\b", t.lower()):
            if w not in stopwords:
                words.append(w)
    if not words:
        return "General Feedback"
    
    from collections import Counter
    top = [item[0] for item in Counter(words).most_common(2)]
    return " ".join(top).title()

def call_groq_with_retry(client: Groq, messages: list[dict]) -> str:
    """Calls Groq API with sequential fallback and exponential backoff retry on rate limits."""
    models = [PRIMARY_MODEL, FALLBACK_MODEL]
    for model in models:
        for attempt in range(3):
            try:
                chat_completion = client.chat.completions.create(
                    messages=messages,
                    model=model,
                    temperature=0.0,  # low temperature for consistency
                    max_tokens=30,    # very short outputs for theme labels
                )
                response = chat_completion.choices[0].message.content
                if response:
                    return response.strip()
            except groq.RateLimitError as e:
                logger.warning(f"Rate limit hit on Groq model {model} (attempt {attempt+1}): {e}")
                # Exponential backoff retry: 2s, 4s, 8s
                sleep_time = 2 ** (attempt + 1)
                time.sleep(sleep_time)
            except Exception as e:
                logger.warning(f"Error calling Groq model {model} (attempt {attempt+1}): {e}")
                time.sleep(2)
    # Raise error if all retries and fallbacks fail
    raise RuntimeError("All Groq API attempts and models failed.")

def generate_theme_label(client: Groq | None, cluster_texts: list[str], existing_labels: list[str] = None) -> str:
    """Generates a short theme label for a set of reviews using Groq or offline fallback."""
    # Truncate each review to a max of 150 characters to save tokens (TPM/TPD mitigation)
    truncated_reviews = [text[:150].strip() + ("..." if len(text) > 150 else "") for text in cluster_texts]
    
    def normalize_label(l: str) -> str:
        return re.sub(r'\s+', ' ', l.strip().lower())

    if not client:
        offline_label = clean_label(extract_keyphrases_offline(cluster_texts))
        if existing_labels:
            base_label = offline_label
            suffix_counter = 1
            norm_existing = [normalize_label(x) for x in existing_labels]
            while normalize_label(offline_label) in norm_existing:
                suffix_counter += 1
                offline_label = clean_label(f"{base_label} Detail {suffix_counter}")
        return offline_label
        
    reviews_formatted = "\n".join([f"- {rev}" for rev in truncated_reviews])
    
    system_prompt = (
        "You are a product feedback classifier. Generate a 2-4 word theme label "
        "(e.g., 'App Performance', 'Withdrawal Experience', 'High Brokerage Fees') "
        "summarizing the core issue or topic described in the reviews. "
        "Respond ONLY with the theme label itself. "
        "Do NOT write any introduction, description, quote marks, or markdown."
    )
    
    user_prompt = f"Reviews:\n{reviews_formatted}\n\nTheme Label:"
    if existing_labels:
        avoid_str = ", ".join([f"'{l}'" for l in existing_labels])
        user_prompt += f"\n\nCRITICAL: The theme label MUST be different from these existing labels: {avoid_str}. Do NOT repeat or paraphrase these. Make it distinct and specific."
    
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt}
    ]
    
    try:
        raw_label = call_groq_with_retry(client, messages)
        label = clean_label(raw_label)
        
        # If duplicate, try a retry with a stronger warning
        if existing_labels:
            norm_existing = [normalize_label(x) for x in existing_labels]
            if normalize_label(label) in norm_existing:
                logger.warning(f"Duplicate theme label generated: '{label}'. Retrying with stronger avoidance warning...")
                retry_prompt = user_prompt + f"\n\nFAILED PREVIOUS ATTEMPT: You generated '{label}' which is a duplicate of an existing theme. You MUST generate a completely different 2-4 word label representing this specific cluster."
                messages[1]["content"] = retry_prompt
                time.sleep(2.0)
                raw_label = call_groq_with_retry(client, messages)
                label = clean_label(raw_label)
        return label
    except Exception as e:
        logger.warning(f"Groq theme labeling failed: {e}. Falling back to offline extraction.")
        offline_label = clean_label(extract_keyphrases_offline(cluster_texts))
        if existing_labels:
            base_label = offline_label
            suffix_counter = 1
            norm_existing = [normalize_label(x) for x in existing_labels]
            while normalize_label(offline_label) in norm_existing:
                suffix_counter += 1
                offline_label = clean_label(f"{base_label} Detail {suffix_counter}")
        return offline_label

def cluster_reviews(embeddings: np.ndarray, clean_reviews_df: pd.DataFrame, max_clusters: int = 5) -> dict:
    """
    Groups clean reviews into themes using K-Means.
    Auto-selects optimal k using silhouette score for k in [5, max_clusters] (k=2 is excluded).
    Queries Groq sequentially (with 2s delay) to label the top 5 themes.
    
    Returns a dict with structured theme metadata.
    """
    N = len(clean_reviews_df)
    if N < 3:
        raise ValueError("Cannot cluster a corpus with fewer than 3 reviews.")
        
    # Standardize maximum clusters based on corpus size
    k_min = 5 if N >= 5 else 3
    k_max = min(max(5, max_clusters), N - 1)
    if k_max < k_min:
        k_max = k_min
        
    logger.info(f"Selecting optimal k in range [{k_min}, {k_max}] using Silhouette Score...")
    
    best_k = k_min
    best_score = -1.0
    best_labels = None
    best_kmeans = None
    
    # Auto-select optimal k (k=2 is excluded because it splits strictly by sentiment)
    for k in range(k_min, k_max + 1):
        kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
        labels = kmeans.fit_predict(embeddings)
        score = silhouette_score(embeddings, labels)
        logger.info(f"k = {k} | Silhouette Score: {score:.4f}")
        
        if score > best_score:
            best_score = score
            best_k = k
            best_labels = labels
            best_kmeans = kmeans
            
    logger.info(f"Selected optimal k = {best_k} (Silhouette Score: {best_score:.4f})")
    
    # Map reviews into their respective clusters
    df = clean_reviews_df.copy()
    df["cluster"] = best_labels
    
    # Calculate distance to centroids to find closest reviews
    centroids = best_kmeans.cluster_centers_
    
    # Get cluster sizes and sort clusters by size descending
    cluster_counts = df["cluster"].value_counts()
    sorted_cluster_ids = cluster_counts.index.tolist()
    
    # We surface the top 5 themes, so we label the top 5 clusters by size
    top_cluster_ids = sorted_cluster_ids[:5]
    
    logger.info("Initializing Groq client for theme labeling...")
    groq_client = get_groq_client()
    
    themes_metadata = []
    existing_labels = []
    
    for idx, cluster_id in enumerate(top_cluster_ids):
        # Filter reviews belonging to this cluster
        cluster_indices = df[df["cluster"] == cluster_id].index.tolist()
        cluster_df = df.loc[cluster_indices]
        cluster_embs = embeddings[cluster_indices]
        centroid = centroids[cluster_id]
        
        # Calculate Euclidean distances to centroid
        distances = np.linalg.norm(cluster_embs - centroid, axis=1)
        # Sort relative indices by distance
        sorted_relative_idx = np.argsort(distances)
        # Take the top 5 closest global indices
        top_5_relative = sorted_relative_idx[:5]
        top_5_global = [cluster_indices[i] for i in top_5_relative]
        
        # Get representative review texts for labeling
        representative_texts = df.loc[top_5_global, "review_text"].tolist()
        
        # Call Groq sequentially with a 2-second sleep delay (RPM/TPM limit mitigation)
        if idx > 0 and groq_client:
            logger.info("Sleeping 2 seconds before next Groq request to respect rate limits...")
            time.sleep(2.0)
            
        logger.info(f"Labeling Cluster {cluster_id} (Size: {len(cluster_df)})...")
        label = generate_theme_label(groq_client, representative_texts, existing_labels)
        
        # Robust programmatic deduplication to guarantee uniqueness and avoid deterministic LLM retry loops
        def normalize_label(l: str) -> str:
            return re.sub(r'\s+', ' ', l.strip().lower())
        
        norm_label = normalize_label(label)
        norm_existing = [normalize_label(x) for x in existing_labels]
        
        if norm_label in norm_existing:
            base_label = label
            suffix_counter = 1
            while norm_label in norm_existing:
                suffix_counter += 1
                label = f"{base_label} {suffix_counter}"
                norm_label = normalize_label(label)
            
        logger.info(f"Generated Label: '{label}'")
        existing_labels.append(label)
        
        themes_metadata.append({
            "id": int(cluster_id),
            "label": label,
            "size": int(len(cluster_df)),
            "review_indices": [int(i) for i in cluster_indices]
        })
        
    return {
        "optimal_k": best_k,
        "silhouette_score": float(best_score),
        "themes": themes_metadata
    }

def main():
    load_dotenv()
    
    cleaned_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../data/cleaned"))
    reviews_file = os.path.join(cleaned_dir, "reviews_clean.json")
    embeddings_file = os.path.join(cleaned_dir, "embeddings_clean.npy")
    output_file = os.path.join(cleaned_dir, "themes_metadata.json")
    
    if not os.path.exists(reviews_file) or not os.path.exists(embeddings_file):
        logger.error("Cleaned reviews or embeddings file not found. Run clean & embed first.")
        sys.exit(1)
        
    df = pd.read_json(reviews_file)
    embeddings = np.load(embeddings_file)
    
    logger.info(f"Loaded {len(df)} reviews and embeddings matrix of shape {embeddings.shape}.")
    
    try:
        result = cluster_reviews(embeddings, df, max_clusters=5)
        
        # Save output themes metadata
        with open(output_file, "w") as f:
            json.dump(result, f, indent=2)
            
        logger.info(f"Themes metadata saved successfully to {output_file}")
    except Exception as e:
        logger.error(f"Failed to cluster reviews: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
